### ISSUE TITLE
iOS Liveness mode

### ISSUE THREAD

**Issue by EddyDunda** [voiceittech/VoiceIt2-React-Native-SDK#5]
When i tried make face verification with liveness prop (liveness: true) i just stucked on this screen:
![2021-01-12 15 27 00](https://user-images.githubusercontent.com/69241200/104320163-a5763500-54ea-11eb-83a2-4cc9a6dfa0c1.jpg)
P.S Without liveness mode (liveness: false) i have successfully verified my user.
Here my code:
``
Voiceit.encapsulatedFaceVerification(
        voiceItUserId,
        'en-US',
        true,
        false,
        res => {
          console.log(res, 'Res');
        }
      );
``

**Comment by hasismaeel5** [comment]
Hi. Did you make sure that the parameters are in the right order?

**Comment by EddyDunda** [comment]
@hasismaeel5  hm, i guess a have right order. Here code from your SDK for iOS:

```
RCT_EXPORT_METHOD(encapsulatedFaceVerification:(NSString *)userId
                          contentLanguage:(NSString *) contentLanguage
                          doLivenessDetection:(BOOL)doLivenessDetection
                          doAudioPrompts:(BOOL)doAudioPrompts
                          callback:(RCTResponseSenderBlock)callback)
{
        dispatch_async(dispatch_get_main_queue(), ^(){
    [myVoiceit encapsulatedFaceVerification: userId doLivenessDetection: doLivenessDetection
                          doAudioPrompts: doAudioPrompts
                         contentLanguage: contentLanguage
    userVerificationCancelled:^{
        callback(@[@"User Verication Cancelled"]);
    }  userVerificationSuccessful:^(float faceConfidence, NSString * jsonResponse){
        callback(@[@"User Verication Successful"]);
    } userVerificationFailed:^(float faceConfidence, NSString * jsonResponse){
        callback(@[@"User Verication Failed"]);
    }];
    });
}
```

**Comment by hasismaeel5** [comment]
@EddyDunda  So the screenshot you sent above isn't from the Liveness Enabled face verification, it's only shown at normal face verification. Can you please do face liveness again and send in another screenshot of where it get's stuck? Much appreciated

**Comment by EddyDunda** [comment]
@hasismaeel5 , Let's check it:
1. My code without liveness flag:
```
Voiceit.encapsulatedFaceVerification(
    voiceItUserId,
    'en-US',
    false,
    false,
    res => {
      console.log(res, 'Res');
    }
  );
```
Result: 

https://user-images.githubusercontent.com/69241200/104751851-9b5c6c80-575e-11eb-82c6-04b85ed64a3d.mp4


2. My code with liveness flag:
```
Voiceit.encapsulatedFaceVerification(
  voiceItUserId,
  'en-US',
  true,
  false,
  res => {
    console.log(res, 'Res');
  }
);

```
Result: 

https://user-images.githubusercontent.com/69241200/104752053-d9f22700-575e-11eb-89a6-ff698b25e195.mp4

**Comment by hasismaeel5** [comment]
Thanks for the details Eddy. I'm looking into this right now and will reply by evening today

**Comment by EddyDunda** [comment]
@hasismaeel5 Hey, any updates? I see that you released new version.

**Comment by hasismaeel5** [comment]
@EddyDunda  Yes Sorry for the delay, we had other issues with the ios SDK. We actually solved them locally, but stay tuned for another release please. Should take us one or two more days

**Comment by hasismaeel5** [comment]
Hey @EddyDunda. We pushed new version of the ios and react native SDK, so please make a pull on this repo :-)

**Comment by EddyDunda** [comment]
@hasismaeel5 i reinstalled npm package and looks like the problem with crash return. https://github.com/voiceittech/VoiceIt2-React-Native-SDK/issues/2 With liveness flag true i got app crash with Xcode error - Invalid userId. And also without liveness mode (liveness: false) i have successfully verified my user. I guess i have this problem but without app crash. I just reinstalled sdk (npm and pod install) and after that try to make liveness face verification
```
Voiceit.encapsulatedFaceVerification(
  voiceItUserId,
  'en-US',
  true,
  false,
  res => {
    console.log(res, 'Res');
  }
);
```

**Comment by hasismaeel5** [comment]
@EddyDunda  Hmm I cannot recreate this error. Please look at the Demo code again maybe? Ado do a pod deintegrate, pod install in the ios repo. Also make sure the react-native-voiceit version is 1.0.2 in the package.json

**Comment by EddyDunda** [comment]
@hasismaeel5 Unfortunately i am not iOS developer so i have no idea how to debug more, but i found problem. When i tried to run face verification and i got en error from your faceVerificationWithLiveness method in VoiceitAPITwo.m. 
First strings of your code:
```
- (void)faceVerificationWithLiveness:(NSString *)userId
               videoPath:(NSString*)videoPath
                callback:(void (^)(NSString *))callback
                lcoId: (NSString *) lcoId
                pageCategory: (NSString *) pageCategory
{
    NSLog(@"userId here: %@", userId);
    NSLog(@"lcoId here: %@", lcoId);

    if([userId isEqualToString:@""] || ![[self getFirst:userId numChars:4] isEqualToString:@"usr_"] || lcoId == nil){
        @throw [NSException exceptionWithName:@"Cannot Call Face Verification"
                                       reason:@"Invalid userId passed"
                                     userInfo:nil];
        return;
    }
```

Here you can see my NSLogs in your method: 
```
NSLog(@"userId here: %@", userId);
NSLog(@"lcoId here: %@", lcoId);
```

And i have got this logs:
```
2021-01-26 23:28:17.378461+0200 mindAuth[37817:6006405] userId here: usr_3e93ad203784433297befd5bd0ef5ca8
2021-01-26 23:28:17.378655+0200 mindAuth[37817:6006405] lcoId here: (null)
```

So probably i have the problem with IcoId, because this is null.

Also i attach some screenshots:
https://monosnap.com/file/UUxDN6yxZYCyphGUIT4Pa3AtEb5vxy
https://monosnap.com/file/gLH27ZjukKi61wSJoTSsYnrzjr1CNs
https://monosnap.com/file/EA8w8pUDWkLtZIJfioXibt9zgQhL75

**Comment by EddyDunda** [comment]
@hasismaeel5 Also i added another one NSLog:
```
-(void)setLivenessData{
    if(!self.doLivenessDetection) return;
    
    [[self myVoiceIt] getLivenessID:self.userToVerifyUserId countryCode:
     self.contentLanguage callback:^(NSString *response) {
        
        NSDictionary *data = [Utilities getJSONObject:response];
        self.lcoStrings = [data valueForKey:@"lcoStrings"];
        self.isChallengeRetrieved = [data valueForKey:@"success"];
        self.lcoId = [data valueForKey:@"lcoId"];
        NSLog(@"lcoId here self.lcoId: %@", self.lcoId);
```
And got this result:
```
2021-01-26 23:53:24.431710+0200 mindAuth[37971:6013340] lcoId here self.lcoId: (null)
```

**Comment by hasismaeel5** [comment]
@EddyDunda  Hmm so the lcoId is null, and that's most likely because you don't have the latest IOS SDK. Can you please make a search for "2.2.1" in you ios directory of your project?

**Comment by hasismaeel5** [comment]
We pushed a newer version, please use the version 1.0.3 of this react native sdk

**Comment by EddyDunda** [comment]
@hasismaeel5 , nothing new in 1.0.3 version, still have this issue https://github.com/voiceittech/VoiceIt2-React-Native-SDK/issues/5#issuecomment-767847648

**Comment by hasismaeel5** [comment]
@EddyDunda That's weird. Please try a fresh install. Do ```pod deintegrate``` in your ios directory, then ```pod install```. Remove node modules in your project's root directory and do ```npm install```, make sure package.json says "react-native-voiceit" : "1.0.3"
We cannot reproduce this error unfortunately

**Comment by EddyDunda** [comment]
@hasismaeel5 Ok, i will try it again, try yo make hard reset and install. But in general, what is lcoId field, how i can resolve it? Maybe i missed something in my voiceit account? Maybe i have to add payment method? Did you try your sdk on another voiceit account? Maybe you can add some logs in your sdk library to detect user issues? How i can resolve it? Also i don’t know why did you close Android liveness issue?

**Comment by EddyDunda** [comment]
@hasismaeel5 I was trying again and got the same result. For iOS - problem with lcoId field. Adn with android - Error Getting Liveness error.
Android stacktrace:
```
D/Camera: app passed NULL surface
W/Activity: Slow Operation: Activity com.mindauth/com.voiceit.voiceit2.FaceEnrollmentView onPause took 163ms
W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@b94414c
D/FaceVerificationView: Cannot hide action bar
V/AsyncHttpRH: Progress 69 from 69 (100%)
I/ReactNativeJS: '{"message":"Error Getting Liveness Challenge"}', 'Ress'
W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
V/MediaPlayer: resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
    cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer: resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
    cleanDrmObj: mDrmObj=null mDrmSessionId=null
W/MediaPlayer: Couldn't open http://localhost:8081/assets/src/video/video-test.mp4?platform=android&hash=4b0b36934390dff0fdcde4e57ff5cf30: java.io.FileNotFoundException: No content provider: http://localhost:8081/assets/src/video/video-test.mp4?platform=android&hash=4b0b36934390dff0fdcde4e57ff5cf30
V/MediaHTTPService: MediaHTTPService(android.media.MediaHTTPService@b921a0c): Cookies: null
V/MediaHTTPService: makeHTTPConnection: CookieManager created: java.net.CookieManager@26cef55
    makeHTTPConnection(android.media.MediaHTTPService@b921a0c): cookieHandler: java.net.CookieManager@26cef55 Cookies: null
I/DpmTcmClient: RegisterTcmMonitor from: com.android.okhttp.TcmIdleTimerMonitor
V/MediaPlayer: resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
    cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer: resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
    cleanDrmObj: mDrmObj=null mDrmSessionId=null
   ```
  Also maybe you can talk about this issues with native developers?

**Comment by hasismaeel5** [comment]
@EddyDunda  Yes all developers of all SDKs work together on issues like this. Unfortunately we cannot recreate this issue whatsoever now. Please look at the https://github.com/voiceittech/VoiceIt2-React-Native-Demo and try to make your project as close to this as possible (the react version, the other dependency versions, etc). Try a fresh project maybe?

**Comment by EddyDunda** [comment]
@hasismaeel5  Fixed.
Check this issue: #9 (comment)
